remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Chuyao Fu's HomePage
description: Welcome to my homepage! My email: 12310306@mail.sustech.edu.cn
